Movie.create(title: 'The Breakfast Club', genre: 'Comedy', release_year: 1985, image_url: "https://images-na.ssl-images-amazon.com/images/I/81tcpYwaSdL._SY445_.jpg")
Movie.create(title: 'Uncle Buck', genre: 'Comedy', release_year: 1989, image_url: "https://images-na.ssl-images-amazon.com/images/I/51HfPL6rhTL._SY445_.jpg")
Movie.create(title: 'Teen Wolf', genre: 'Comedy', release_year: 1985, image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/2/26/Teen_Wolf.jpg/220px-Teen_Wolf.jpg")
Movie.create(title: 'Above the Law', genre: 'Drama', release_year: 1988, image_url: "https://i.ebayimg.com/images/g/oIsAAOSwYvFZM82I/s-l300.jpg")
Movie.create(title: 'They Live', genre: 'Science Fiction', release_year: 1988, image_url: "https://m.media-amazon.com/images/M/MV5BMTQ3MjM3ODU1NV5BMl5BanBnXkFtZTgwMjU3NDU2MTE@._V1_UX182_CR0,0,182,268_AL_.jpg")
Movie.create(title: 'A Nightmare on Elm Street', genre: 'Horror', release_year: 1984, image_url: "https://resizing.flixster.com/aoGs7-o6WQkeh_H-1s-plnV97TQ=/206x305/v1.bTsxMTYxNDc4OTtqOzE4MTM0OzEyMDA7MzI0OzQzMg")
Movie.create(title: 'Cocktail', genre: 'Drama', release_year: 1988, image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/Cocktail_1988.jpg/220px-Cocktail_1988.jpg")
Movie.create(title: 'Flash Gordon', genre: 'Science Fiction', release_year: 1980, image_url: "https://m.media-amazon.com/images/M/MV5BN2Y4ZDBjMjEtZWQ0OS00NzYyLTg0M2ItMmUzYTEwN2RmMGVlXkEyXkFqcGdeQXVyMjgyOTI1ODY@._V1_UX182_CR0,0,182,268_AL_.jpg")
